name: PR Unit Tests

# on:
#   pull_request:
#     branches: [main, develop]

on:
  push:
    branches: develop

jobs:
  unit-tests:
    runs-on: linux-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 2
          cache: npm # change to pnpm/yarn if needed

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test -- --run
